[profile.default]
solc_version = "0.8.28"
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 100000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_SCAN_API_KEY}", chain = "sepolia" }